name: Build & Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: '14'

jobs:
  BackendTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Backend Tests
        working-directory: spring-backend
        run: ./mvnw test

  FrontendTests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        working-directory: client
        run: npm install
        env:
          CI: true

      - name: Run Frontend Tests
        working-directory: client
        run: npm test
        env:
          CI: true

  EndToEndTests:
    runs-on: ubuntu-latest
    needs: [BackendTests, FrontendTests]
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        working-directory: client
        run: npm install

      - name: Run Frontend Tests
        working-directory: client
        run: npx playwright test src/tests/e2e/*.spec.*js --workers=1