name: Build & Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: '14'

jobs:
#  Backend-Tests:
#    name: Backend Tests
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Run Backend Tests
#        working-directory: spring-backend
#        run: ./mvnw test
#
#  Frontend-Tests:
#    name: Frontend Tests
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Set up Node.js
#        uses: actions/setup-node@v2
#        with:
#          node-version: ${{ env.NODE_VERSION }}
#
#      - name: Install dependencies
#        working-directory: client
#        run: npm install
#
#      - name: Run Frontend Tests
#        working-directory: client
#        run: npm test

  End-To-End-Tests:
    name: End-to-End Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
#    needs: [BackendTests, FrontendTests]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        working-directory: client
        run: npm install

      - name: Start Backend
        working-directory: spring-backend
        run: ./mvnw spring-boot:run &

      - name: Start Client
        working-directory: client
        run: npm start &

      - name: Run E2E Tests
        working-directory: client
        run: sleep 120 && npx playwright test src/tests/e2e/*.spec.*js --workers=1